### ISSUE TITLE
Transfer learning with my own data

### ISSUE THREAD

**Issue by mmejeras** [remega/OMCNN_2CLSTM#2]
Is it possible to perform transfer learning on the pretrained model? Do you have plans to release the train code as well?

Thank you

**Comment by remega** [comment]
Actually, now we don't have a plan to release a clean version of that. If it is really necessary, I may make it, depending on my furture schedule. However, I think it is still practical for a transfer learning, since the detailed architecture and pre-trained weights are included in this repository. If I could be of any further help, please contact me by e-mail jianglai.china@aliyun.com.
